Query multiple tables
elasfarc/Vet-clinic-database pull request #3
Opened 2021-09-23 21:59 UTC by elasfarc

in this PR, I did the following:

- Created owners && species  tables.
- Updated animals tables :
-- Add column species_id which is a foreign key referencing species table
-- Add column owner_id which is a foreign key referencing the owners table
- Write queries (using JOIN)

2021-09-23 22:31 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @elasfarc 

Great work on implementing the project requirements, however there are some issues to be solved before you get approved but you are almost there:muscle:
   
 - The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Changes required :writing_hand: 

         - Please work on the review too

    Cheers and Happy coding!:clap::clap::clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-23 22:31 UTC, Emmyn5600 commented on schema.sql
> +
You should modify the animals table:

- Remove column species:heavy_check_mark:
` - Add column species_id which is a foreign key referencing species table`
` -Add column owner_id which is a foreign key referencing the owners table`

2021-09-23 22:31 UTC, Emmyn5600 commented on data.sql
> +END;
- [ ] Here. we need to get `id from species WHERE name = 'Digimon'`

2021-09-23 22:31 UTC, Emmyn5600 commented on data.sql
> +
- [ ] After setting owner_id, you need to `SELECT id from owners WHERE full_name`

2021-09-24 12:52 UTC, AshakaE commented
### Hi @elasfarc  🙋‍♀️, 

# STATUS APPROVED ✔
Thanks for making the requested changes 🙏🏼
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-24 12:55 UTC, merged